export const LANGUAGES: {code: string, name: string}[] = [
    { "code": "en", "name": "English" },
    { "code": "es", "name": "Spanish" },
    { "code": "fr", "name": "French" },
    { "code": "de", "name": "German" },
    { "code": "zh", "name": "Chinese (Mandarin)" },
    { "code": "ja", "name": "Japanese" },
    { "code": "hi", "name": "Hindi" },
    { "code": "ar", "name": "Arabic" },
    { "code": "pt", "name": "Portuguese" },
    { "code": "ru", "name": "Russian" },
    { "code": "bn", "name": "Bengali" },
    { "code": "ko", "name": "Korean" },
    { "code": "it", "name": "Italian" },
    { "code": "vi", "name": "Vietnamese" },
    { "code": "th", "name": "Thai" },
    { "code": "tr", "name": "Turkish" },
    { "code": "nl", "name": "Dutch" },
    { "code": "el", "name": "Greek" },
    { "code": "pl", "name": "Polish" },
    { "code": "sv", "name": "Swedish" },
    { "code": "hu", "name": "Hungarian" },
    { "code": "fa", "name": "Persian (Farsi)" },
    { "code": "he", "name": "Hebrew" },
    { "code": "id", "name": "Indonesian" },
    { "code": "ms", "name": "Malay" },
    { "code": "tl", "name": "Tagalog (Filipino)" },
    { "code": "uk", "name": "Ukrainian" },
    { "code": "cs", "name": "Czech" },
    { "code": "ro", "name": "Romanian" },
    { "code": "fi", "name": "Finnish" },
    { "code": "no", "name": "Norwegian" },
    { "code": "da", "name": "Danish" },
    { "code": "bg", "name": "Bulgarian" },
    { "code": "sr", "name": "Serbian" },
    { "code": "hr", "name": "Croatian" },
    { "code": "sk", "name": "Slovak" },
    { "code": "sl", "name": "Slovenian" },
    { "code": "et", "name": "Estonian" },
    { "code": "lt", "name": "Lithuanian" },
    { "code": "lv", "name": "Latvian" },
    { "code": "mt", "name": "Maltese" },
    { "code": "is", "name": "Icelandic" },
    { "code": "cy", "name": "Welsh" },
    { "code": "ga", "name": "Irish" }
  ];
  